server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      dialect: org.hibernate.dialect.PostgresSQL95Dialect
  datasource:
    url: jdbc:postgresql://${DB_SERVER}/${POSTGRES_DB}
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  flyway:
    url: jdbc:postgresql://${DB_SERVER}/${POSTGRES_DB}
    schemas: public
    user: postgres
    password: admin
  sql:
    init:
      platform: postgres

---

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
  config:
    activate:
      on-profile: development